version: '3.8'

services:
  app:
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    profiles: [] 